/* bolt402 FFI — auto-generated by cbindgen. Do not edit. */

#ifndef BOLT402_H
#define BOLT402_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to an L402 client.
 */
typedef struct Bolt402Client Bolt402Client;

/**
 * Opaque handle to a mock L402 server.
 */
typedef struct Bolt402MockServer Bolt402MockServer;

/**
 * Opaque handle to an L402 response.
 */
typedef struct Bolt402Response Bolt402Response;

/**
 * Endpoint configuration for the mock server (path + price in sats).
 */
typedef struct Bolt402Endpoint {
  /**
   * Null-terminated endpoint path (e.g. "/api/data").
   */
  const char *path;
  /**
   * Price in satoshis.
   */
  uint64_t price_sats;
} Bolt402Endpoint;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Get the last error message, or null if no error occurred.
 *
 * The returned string is valid until the next FFI call on the same thread.
 * Do **not** free it with `bolt402_string_free`.
 */
const char *bolt402_last_error_message(void);

/**
 * Free a string allocated by bolt402 FFI functions.
 *
 * # Safety
 *
 * `s` must be a pointer returned by a bolt402 FFI function, or null.
 */
void bolt402_string_free(char *s);

/**
 * Create a new mock L402 server with the given endpoints.
 *
 * Returns null on error (check `bolt402_last_error_message`).
 *
 * # Safety
 *
 * `endpoints` must point to `count` valid `Bolt402Endpoint` structs.
 * Each `path` field must be a valid null-terminated C string.
 */
struct Bolt402MockServer *bolt402_mock_server_new(const struct Bolt402Endpoint *endpoints,
                                                  uintptr_t count);

/**
 * Get the URL of the mock server.
 *
 * The returned string is owned by the server and valid until the server is freed.
 * Do **not** free it with `bolt402_string_free`.
 *
 * # Safety
 *
 * `server` must be a valid pointer from `bolt402_mock_server_new`.
 */
const char *bolt402_mock_server_url(const struct Bolt402MockServer *server);

/**
 * Free a mock server.
 *
 * # Safety
 *
 * `server` must be a pointer from `bolt402_mock_server_new`, or null.
 */
void bolt402_mock_server_free(struct Bolt402MockServer *server);

/**
 * Create a client connected to a mock server.
 *
 * The mock server must have been created with `bolt402_mock_server_new`.
 * Returns null on error.
 *
 * # Safety
 *
 * `server` must be a valid pointer from `bolt402_mock_server_new`.
 */
struct Bolt402Client *bolt402_client_new_mock(const struct Bolt402MockServer *server,
                                              uint64_t max_fee_sats);

/**
 * Free a client.
 *
 * # Safety
 *
 * `client` must be a pointer from `bolt402_client_new_mock`, or null.
 */
void bolt402_client_free(struct Bolt402Client *client);

/**
 * Send a GET request through the L402 client.
 *
 * Returns null on error (check `bolt402_last_error_message`).
 *
 * # Safety
 *
 * `client` must be a valid client pointer. `url` must be a valid C string.
 */
struct Bolt402Response *bolt402_client_get(struct Bolt402Client *client, const char *url);

/**
 * Send a POST request through the L402 client.
 *
 * `body` may be null for requests with no body.
 * Returns null on error (check `bolt402_last_error_message`).
 *
 * # Safety
 *
 * `client` must be a valid client pointer. `url` must be a valid C string.
 * `body` must be a valid C string or null.
 */
struct Bolt402Response *bolt402_client_post(struct Bolt402Client *client,
                                            const char *url,
                                            const char *body);

/**
 * Get the HTTP status code from a response.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
uint16_t bolt402_response_status(const struct Bolt402Response *response);

/**
 * Check whether a Lightning payment was made for this response.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
bool bolt402_response_paid(const struct Bolt402Response *response);

/**
 * Get the response body as a C string.
 *
 * The returned string is owned by the response. Do not free it separately.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
const char *bolt402_response_body(const struct Bolt402Response *response);

/**
 * Check whether the response contains a payment receipt.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
bool bolt402_response_has_receipt(const struct Bolt402Response *response);

/**
 * Get the amount paid in satoshis (0 if no receipt).
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
uint64_t bolt402_response_receipt_amount_sats(const struct Bolt402Response *response);

/**
 * Get the routing fee in satoshis (0 if no receipt).
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
uint64_t bolt402_response_receipt_fee_sats(const struct Bolt402Response *response);

/**
 * Get the payment hash from the receipt.
 *
 * Returns null if no receipt. The string is owned by the response.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
const char *bolt402_response_receipt_payment_hash(const struct Bolt402Response *response);

/**
 * Get the preimage (proof of payment) from the receipt.
 *
 * Returns null if no receipt. The string is owned by the response.
 *
 * # Safety
 *
 * `response` must be a valid response pointer.
 */
const char *bolt402_response_receipt_preimage(const struct Bolt402Response *response);

/**
 * Free a response.
 *
 * # Safety
 *
 * `response` must be a pointer from `bolt402_client_get` or `bolt402_client_post`, or null.
 */
void bolt402_response_free(struct Bolt402Response *response);

/**
 * Get the total amount spent by the client in satoshis.
 *
 * # Safety
 *
 * `client` must be a valid client pointer.
 */
uint64_t bolt402_client_total_spent(const struct Bolt402Client *client);

/**
 * Get all receipts as a JSON array string.
 *
 * The caller must free the returned string with `bolt402_string_free`.
 * Returns null on error.
 *
 * # Safety
 *
 * `client` must be a valid client pointer.
 */
char *bolt402_client_receipts_json(const struct Bolt402Client *client);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BOLT402_H */
